CREATE TABLE discovery_strategies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    team_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(160) NOT NULL,
    strategy_type VARCHAR(32) NOT NULL,
    platform VARCHAR(32) NOT NULL,
    config_json JSON NOT NULL,
    schedule VARCHAR(64) NOT NULL DEFAULT 'manual',
    timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
    status VARCHAR(16) NOT NULL DEFAULT 'disabled',
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_discovery_strategies_team_name (team_id, name),
    KEY idx_discovery_strategies_team_status (team_id, status),
    CONSTRAINT fk_discovery_strategies_team FOREIGN KEY (team_id) REFERENCES operation_teams(id),
    CONSTRAINT fk_discovery_strategies_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT chk_discovery_strategies_type CHECK (strategy_type IN ('keyword', 'author')),
    CONSTRAINT chk_discovery_strategies_status CHECK (status IN ('enabled', 'disabled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE crawl_tasks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    team_id BIGINT UNSIGNED NOT NULL,
    strategy_id BIGINT UNSIGNED NULL,
    task_id VARCHAR(64) NULL,
    task_type VARCHAR(32) NOT NULL,
    platform VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    snapshot_json JSON NOT NULL,
    stats_json JSON NOT NULL,
    error_message VARCHAR(500) NULL,
    started_at DATETIME(6) NULL,
    finished_at DATETIME(6) NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_crawl_tasks_task_id (task_id),
    KEY idx_crawl_tasks_team_created (team_id, created_at),
    KEY idx_crawl_tasks_strategy_created (strategy_id, created_at),
    CONSTRAINT fk_crawl_tasks_team FOREIGN KEY (team_id) REFERENCES operation_teams(id),
    CONSTRAINT fk_crawl_tasks_strategy FOREIGN KEY (strategy_id) REFERENCES discovery_strategies(id),
    CONSTRAINT fk_crawl_tasks_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT chk_crawl_tasks_status CHECK (status IN ('pending', 'running', 'success', 'failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
