CREATE TABLE local_agent_binding_tickets (
    id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    token_hash CHAR(64) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    used_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_local_agent_binding_ticket_hash (token_hash),
    KEY idx_local_agent_binding_ticket_expiry (expires_at, used_at),
    CONSTRAINT fk_local_agent_binding_ticket_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_local_agent_binding_ticket_session FOREIGN KEY (session_id) REFERENCES user_sessions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE local_agent_nodes (
    id VARCHAR(64) NOT NULL,
    agent_id VARCHAR(128) NOT NULL,
    device_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    mode VARCHAR(16) NOT NULL,
    agent_version VARCHAR(32) NOT NULL,
    contract_major_version VARCHAR(16) NOT NULL,
    contract_revision VARCHAR(32) NOT NULL,
    credential_hash CHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    operating_system VARCHAR(32) NULL,
    cpu_architecture VARCHAR(32) NULL,
    python_version VARCHAR(32) NULL,
    ffmpeg_status VARCHAR(32) NULL,
    ffmpeg_version VARCHAR(32) NULL,
    workdir_status VARCHAR(32) NULL,
    disk_status VARCHAR(32) NULL,
    disk_free_megabytes BIGINT NULL,
    bitbrowser_status VARCHAR(32) NULL,
    reported_main_user_id VARCHAR(255) NULL,
    registered_at DATETIME(6) NOT NULL,
    last_heartbeat_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_local_agent_node_credential_hash (credential_hash),
    KEY idx_local_agent_node_user_status (user_id, status, last_heartbeat_at),
    KEY idx_local_agent_node_device (user_id, device_id, registered_at),
    CONSTRAINT fk_local_agent_node_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_local_agent_node_session FOREIGN KEY (session_id) REFERENCES user_sessions(id),
    CONSTRAINT chk_local_agent_node_mode CHECK (mode = 'local'),
    CONSTRAINT chk_local_agent_node_status CHECK (status IN ('online', 'draining', 'replaced'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE browser_profile_runtime_presence (
    id VARCHAR(64) NOT NULL,
    profile_id VARCHAR(64) NOT NULL,
    bit_profile_id VARCHAR(255) NOT NULL,
    node_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    main_user_id VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    last_seen_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_browser_profile_runtime_presence_profile (profile_id),
    KEY idx_browser_profile_runtime_presence_node (node_id, status, last_seen_at),
    KEY idx_browser_profile_runtime_presence_user (user_id, status, last_seen_at),
    KEY idx_browser_profile_runtime_presence_main_user (main_user_id, status, last_seen_at),
    CONSTRAINT fk_browser_profile_runtime_presence_profile FOREIGN KEY (profile_id) REFERENCES browser_profiles(id),
    CONSTRAINT fk_browser_profile_runtime_presence_node FOREIGN KEY (node_id) REFERENCES local_agent_nodes(id),
    CONSTRAINT fk_browser_profile_runtime_presence_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_browser_profile_runtime_presence_status CHECK (status IN ('visible', 'not_visible'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
