CREATE TABLE media_accounts (
    id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    game_id VARCHAR(128) NOT NULL,
    platform VARCHAR(32) NOT NULL,
    platform_account_id VARCHAR(255) NULL,
    name VARCHAR(255) NULL,
    avatar_url VARCHAR(2048) NULL,
    browser_profile_id VARCHAR(64) NULL,
    identification_status VARCHAR(32) NOT NULL DEFAULT 'pending_identification',
    duplicate_of_account_id VARCHAR(64) NULL,
    business_status VARCHAR(32) NOT NULL DEFAULT 'enabled',
    login_status VARCHAR(32) NOT NULL DEFAULT 'unknown',
    original_cookie LONGTEXT NULL,
    active_cookie LONGTEXT NULL,
    cookie_status VARCHAR(32) NULL,
    active_cookie_updated_at DATETIME(6) NULL,
    last_checked_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_media_accounts_user_platform_identity (user_id, platform, platform_account_id),
    KEY idx_media_accounts_user_game (user_id, game_id),
    UNIQUE KEY uq_media_accounts_profile_platform (browser_profile_id, platform),
    KEY idx_media_accounts_status (business_status, identification_status),
    CONSTRAINT fk_media_accounts_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_media_accounts_duplicate FOREIGN KEY (duplicate_of_account_id) REFERENCES media_accounts (id),
    CONSTRAINT chk_media_accounts_platform CHECK (platform IN ('douyin', 'bilibili', 'baijiahao')),
    CONSTRAINT chk_media_accounts_identification CHECK (identification_status IN ('pending_identification', 'identified', 'duplicate')),
    CONSTRAINT chk_media_accounts_business_status CHECK (business_status IN ('enabled', 'disabled', 'retired')),
    CONSTRAINT chk_media_accounts_login_status CHECK (login_status IN ('unknown', 'normal', 'not_logged_in', 'verification_needed', 'expired', 'restricted', 'account_mismatch', 'environment_error'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE media_account_tags (
    id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    media_account_id VARCHAR(64) NOT NULL,
    tag_name VARCHAR(64) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_media_account_tags_owner_account_name (user_id, media_account_id, tag_name),
    KEY idx_media_account_tags_name (user_id, tag_name, media_account_id),
    CONSTRAINT fk_media_account_tags_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_media_account_tags_account FOREIGN KEY (media_account_id) REFERENCES media_accounts (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
