name = 'primary'
charset = 'utf8mb4'
database = 'wt_media_cloud'
host = '127.0.0.1'
location = 'Local'
parse_time = true
password = 'root123'
port = 3306
username = 'root'

[pool]
max_idle = 10
max_lifetime = '30m'
max_open = 50
