import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const read = (name) => readFileSync(new URL(`./${name}`, import.meta.url), 'utf8')

describe('discovery strategy and task pages', () => {
  it('presents strategies as rules with business language and stat cards', () => {
    const source = read('DiscoveryStrategiesPage.vue')
    expect(source).toContain('strategy_type')
    expect(source).toContain('关键词')
    expect(source).toContain('作者（维护中）')
    expect(source).toContain('value="author" disabled')
    expect(source).toContain("row.strategy_type === 'author'")
    expect(source).toContain('策略总数')
    expect(source).toContain('启用策略')
    expect(source).toContain('今日执行')
    expect(source).toContain('自动素材')
    expect(source).toContain('搜索策略名称')
    expect(source).toContain("colKey: 'id'")
    expect(source).toContain('required-mark')
    expect(source).toContain('所属游戏')
    expect(source).toContain('listGames')
    expect(source).toContain('gameName')
    expect(source).toContain('查询')
    expect(source).toContain('重置')
    expect(source).toContain('挖掘规则')
    expect(source).toContain('转素材规则')
    expect(source).toContain('最近效果')
    expect(source).toContain('赞≥')
    expect(source).toContain('藏≥')
    expect(source).toContain('latestSummary')
    expect(source).toContain('value="AND"')
    expect(source).toContain('value="OR"')
    expect(source).toContain('like_threshold')
    expect(source).toContain('favorite_threshold')
    expect(source).toContain('openKeywords')
    expect(source).toContain('openAuthors')
    expect(source).toContain('KeywordTags')
    expect(source).toContain('strategy-rule-link')
    expect(source).toContain('关键词配置')
    expect(source).toContain('作者配置')
  })

  it('keeps strategy actions to five with run/edit/delete state control', () => {
    const source = read('DiscoveryStrategiesPage.vue')
    expect(source).toContain('执行')
    expect(source).toContain('记录')
    expect(source).toContain('编辑')
    expect(source).toContain('复制')
    expect(source).toContain('删除')
    expect(source).toContain('deleteStrategy')
    expect(source).toContain('openCopy')
    expect(source).toContain('isRunning')
    expect(source).not.toContain('立即执行')
    expect(source).not.toContain('内容结果')
    expect(source).not.toContain('执行记录')
  })

  it('renders tasks with business naming, results, and a tabbed detail drawer', () => {
    const source = read('CrawlTasksPage.vue')
    expect(source).toContain('任务名称')
    expect(source).toContain('来源策略')
    expect(source).toContain('触发方式')
    expect(source).toContain('发现结果')
    expect(source).toContain('执行时间')
    expect(source).toContain('taskName')
    expect(source).toContain('strategyName')
    expect(source).toContain('triggerLabel')
    expect(source).toContain('foundSummary')
    expect(source).toContain('详情')
    expect(source).toContain('重试')
    expect(source).toContain('结果概览')
    expect(source).toContain('发现内容')
    expect(source).toContain('执行过程')
    expect(source).toContain('异常记录')
    expect(source).toContain('timeline')
    expect(source).toContain('exceptions')
    expect(source).toContain('重新执行')
    expect(source).toContain('client.retryFailed')
    expect(source).toContain('待审核')
    expect(source).toContain('自动转素材')
    expect(source).toContain('执行中')
    expect(source).toContain('部分成功')
    expect(source).toContain('truncateTitle')
    expect(source).toContain('processing_status')
    expect(source).not.toContain('查看详情')
    expect(source).not.toContain('重试失败项')
    expect(source).not.toContain('策略快照')
    expect(source).not.toContain('关联原任务')
  })
})
